-- Add schedule and generated output columns to report_runs
ALTER TABLE report_runs
  ADD COLUMN IF NOT EXISTS schedule_cron TEXT,
  ADD COLUMN IF NOT EXISTS last_run_at   TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS output        JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN report_runs.schedule_cron IS 'Optional cron expression for scheduled batch exports.';
COMMENT ON COLUMN report_runs.last_run_at   IS 'Timestamp of the most recent successful run.';
COMMENT ON COLUMN report_runs.output        IS 'JSON payload generated by the last run (stats, SLA snapshot, etc.).';
